language: go
go:
  - 1.7
sudo: required
dist: trusty
before_install:
  - sudo apt-get install -qq fuse
  - sudo modprobe fuse
  - sudo /bin/sh -c 'echo user_allow_other > /etc/fuse.conf'
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf
  - go get github.com/mattn/goveralls
    # for testing chown, we need the travis user to be in 'users'
  - sudo usermod -a -G users $USER
script:
  - go get -t -v ./...
    # for testing chown, we need the effective travis user to be in 'users'
  - groups
  - go test -v ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
